# Generated by Django 4.1.7 on 2023-03-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='proco_promocional',
            new_name='preco_promocional',
        ),
    ]
