# Generated by Django 4.1.7 on 2023-04-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_rename_proco_promocional_itempedido_preco_promocional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='quatidade',
            new_name='quantidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
